//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpelletjesEntities : DbContext
    {
        public SpelletjesEntities()
            : base("name=SpelletjesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sessie> Sessies { get; set; }
        public virtual DbSet<Speler> Spelers { get; set; }
        public virtual DbSet<Spellen> Spellens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uitslagen> Uitslagens { get; set; }
        public virtual DbSet<added> addeds { get; set; }
    }
}
